### ISSUE TITLE
Table does not wrap

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-jwt#70]
The table used by the frontend in the MP JWT guide to display various information about the user including the JWT doesn't wrap.  Because the value of the JWT is long, it extends beyond the width of the window.

It should wrap at the width of the browser window.

**Comment by kinueng** [comment]
@yeekangc Is the problematic table on openliberty.io?  I could not easy tell which table is having issues.

**Comment by yeekangc** [comment]
@kinueng, not the website but in the sample app used by the guide.

**Comment by TiagoF99** [comment]
I see the issue and will take a look at it to address it.

**Comment by TiagoF99** [comment]
<img width="1437" alt="Screen Shot 2020-07-06 at 12 09 52 PM" src="https://user-images.githubusercontent.com/45250015/86614872-a3eb1380-bf81-11ea-993f-7d3aff4a9391.png">

- Now the application looks like this. The issue has been fixed. I also made each column width 50% of the screen size so that it is more readable against smaller screen sizes. 
- Tested UI on firefox and safari
